/**
 * Normalisation for filesystem paths arriving from a tool call.
 *
 * Paths reach these servers by being typed into MCP Inspector, pasted into a
 * chat message, or generated by an LLM — none of which are as tidy as a shell.
 * Two things go wrong often enough to be worth handling rather than rejecting:
 *
 *   " /Users/me/project"  — a stray leading space. `path.resolve` does not treat
 *                           this as absolute, so it silently joins it onto the
 *                           process cwd and produces a nonsense path like
 *                           `/cwd/ /Users/me/project`.
 *   "~/project"           — a tilde. Shells expand this; Node does not, so
 *                           `resolve` yields a literal `./~/project`.
 */

import { homedir } from "node:os";
import { resolve } from "node:path";

export function normalizePath(input: string): string {
  // Strip surrounding whitespace and the quotes that come with a copy-paste.
  let path = input.trim().replace(/^["']|["']$/g, "").trim();

  if (path === "~") {
    path = homedir();
  } else if (path.startsWith("~/")) {
    path = resolve(homedir(), path.slice(2));
  }

  return resolve(path);
}
